import random
score=0
wi=0
t=['heads','tails']
a=[1,2,4,6,3]
r=24
print("*->PLEASE READ BELOW<-*")
print("*->SOME RANDOM NUMBER WILL BE GENERATED BY SYSTEM IF YOU CLICK THAT NUM YOU WILL LOSE WICKET")
print("*->IF YOU CLICK GREATER THAN 6 ALSO YOU WILL LOSE THE WICKET")
print("*->YOU HAVE 4 OVERS AND 5 WICKETS")
while True:
    tt=random.choice(t)
    print(tt)
    p1=input("please enter your name:")
    for i in range(r):
        if(wi==5):
            break
        b=random.choice(a)
        aa=int(input("enter the score:"))
        if(aa==b or aa>=7):
            wi+=1
            print("Remaining wickets:",5-wi)
        elif(aa==5):
            print("no run")
        else:
            score=score+aa
    print("total score:",score,"/",wi)
    print("second innings start")
    print("your have to chase:",score,"RUNS In 4 Overs")
    wi2=0
    score2=0
    p2=input("please enter your name:")
    for i in range(r):
        if(wi2==5):
            break
        elif(score2>score):
            print(p1,"won the match")
            break
        b=random.choice(a)
        aa=int(input("enter the score:"))
        if(aa==b or aa>=7):
            wi2+=1
            print("Remaining wickets:",5-wi2)
        elif(aa==5):
            print("no run")
        else:
            score2=score2+aa
    print("your total score is:",score2,"/",wi2)
    if(score2>score):
        print(p2,"won the match")
    elif(score2<score):
        print(p1,"won the match")
    else:
        print("match draw")
    print("if you want to play again press :1")
    hh=int(input("enter the number:"))
    if(hh!=1):
        break
print("Game over Thank You")

    
